# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-05-18 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
from django.contrib.postgres.operations import HStoreExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ]

    operations = [

        HStoreExtension(),

    ]
