# Generated by Django 2.0.6 on 2018-06-07 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180607_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='attributes',
        ),
    ]
