# Generated by Django 2.0.6 on 2018-06-07 11:35

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_package_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
    ]
